name: CI/CD WORKFLOW

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto' # Matches your teacher's configuration

      # Step 3: Build with Maven
      - name: Build with Maven
        env:
          DEPLOYED: ${{ secrets.DEPLOYED }} # Set to 'true' or left empty depending on your deployment environment
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ISSUER: ${{ secrets.ISSUER }}
          TOKEN_EXPIRE_TIME: ${{ secrets.TOKEN_EXPIRE_TIME }}
        run: mvn --batch-mode clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Set up Docker Buildx (required for building multi-platform Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 6: Build and push Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trip_planner_api:latest

      # Step 7: Placeholder for Deployment to Server
      - name: Deploy to Server
        run: |
          echo "Deployment instructions go here"
